twig:
    default_path: '%kernel.project_dir%/templates'
    # mise en forme du formulaire via Bootstrap 5.0
    form_themes: ['bootstrap_5_layout.html.twig']


when@test:
    twig:
        strict_variables: true
